### ISSUE TITLE
Could you provide full details of dataset and code?

### ISSUE THREAD

**Issue by JinanZou** [midas-research/man-sf-emnlp#4]
Hi I would like to follow your work, however, the dataset and code are not clear. Could you update it asap if possible? 
Cheers,

**Comment by sia-watsonlee** [comment]
this paper has some serious issues i think. there is also no file called graph.npy.

**Comment by JinanZou** [comment]
I found the same issue in some other papers. And No reply from all authors
of the email. 😂😂

**Comment by sia-watsonlee** [comment]
they just disappear after their paper get accepted i think.

**Comment by ramitsawhney27** [comment]
The graph collection methodology is described by scraping Wikimedia. unfortunately, due to privacy restrictions on the original data we can not re disseminate that data - we have asked and were denied permission. The closest we can do is describe the method for parsing the same graph.
